//NAVIGATION
export const TOOGLE_NAVIGATION = 'TOOGLE_NAVIGATION';
export const TOOGLE_LOADING = 'TOOGLE_LOADING';

//lOADING EFFECTS
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';

//FETCH DATA FROM SERVER

export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';

//ORDERS ACTION
export const REQUEST_ORDERS = 'REQUEST_ORDERS';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
