//NAVIGATION
export const TOOGLE_NAVIGATION = 'TOOGLE_NAVIGATION';
export const TOOGLE_LOADING = 'TOOGLE_LOADING';

//lOADING EFFECTS
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';

//FETCH DATA FROM SERVER

export const GET_USER_DATA = 'GET_USER_DATA';